### PR TITLE
Update travis

### PR DESCRIPTION
**Pull request by tbabej**
TaskWarrior 2.4.0 made it out!

### CODE REVIEW

**Comment by robgolding63** [comment]
Did the merge go wonky here? Not sure if all the changes are intentional or if git is being weird. You're able to do the merge yourself now though so feel free when you're happy :)

I'll make a 0.7.0 release if you wish when the main branch is all sorted and tests pass. Welcome to tasklib!

**Comment by tbabej** [comment]
I rebased the pull request on top of current develop branch, will merge once the Travis build passes.

**Comment by tbabej** [comment]
A fix for the develop branch of TaskWarrior was necessary. Tests pass now, merging.

**Comment by tbabej** [comment]
Just to explain the mess, I miss-clicked and deleted-and-closed the branch instead of merging and closing.

**Pull request merged**
